[package]
name = "tonapi"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Rust SDK designed to access the TonAPI REST endpoints"
repository = "https://github.com/liketurbo/tonapi-rs"
readme = "README.md"
categories = ["cryptography::cryptocurrencies", "web-programming::http-client"]
keywords = ["blockchain", "ton", "tonapi"]

[dependencies]
generated_tonapi = { path = "generated-tonapi", package = "openapi" }

[build-dependencies]
reqwest = { version = "0.11.22", features = ["blocking"] }

[dev-dependencies]
tokio = { version = "1.34.0", features = ["full"] }